name: AthenaJobs
version: '${project.version}'
main: lunatic.athenajobs.Main
api-version: '1.20'
commands:
  helpjobs:
    description: JobsHelp
  givebooster:
    permission: op
    description: Give Booster
  terimakasih:
    description: Berterimakasih!
  prestige:
    description: Level up prestige
  athenajobs:
    description: Reloads the AthenaJobs plugin configuration
    usage: /athenajobs reload
    permission: athenajobs.reload